### ISSUE TITLE
Лишняя валидация

### ISSUE THREAD

**Issue by casa7x** [AnnLuschik/lesson-14-js#1]
https://github.com/AnnLuschik/lesson-14-js/blob/58f23cc5840efb14986012d1ce10e42940cb4e22/script.js#L89

Непонимаю этой валидации, при входе. Когда пользователь входит, у него не надо проверять длину пароля и прочее. Тебе по сути надо запросить логин и пароль при логине и потом их сверить, У тебя есть несколько вариантов - "Пользователя такого нет", "Неверный пароль","Успешный вход". Можно ещё на пустые поля проверить. Первым делом, проряешь позитивный вариант. Если логин и пароль совпадают, то пропускаешь, а вот если нет, то уже определяешь, что именно неверно,

**Comment by AnnLuschik** [comment]
Идея была в том, что пользователь, например, мог перепутать раскладку клавиатуры, и при выводе сообщения, что пароль должен состоять из латинских букв, он бы быстрее понял, что не так. Дополнительные проверки при входе убраны.
"Первым делом, проверяешь позитивный вариант. Если логин и пароль совпадают, то пропускаешь, а вот если нет, то уже определяешь, что именно неверно," // так всё и было.
