### ISSUE TITLE
Определение професии

### ISSUE THREAD

**Issue by casa7x** [AnnLuschik/lesson-14-js#2]
https://github.com/AnnLuschik/lesson-14-js/blob/58f23cc5840efb14986012d1ce10e42940cb4e22/script.js#L134

Я бы запрашивал профессию на этапе сортировки по разным массивам. Потом в отдельном for уже начал бы искать детей. 
Получается нормальное разделение на подзадачи. Всё таки поиск детей, более крупная задача, чем просто спросить профессию., она может масштабироваться, могут добавиться нюансы, в твоём случае это делать сложнее. Здесь кстати удобнее использовать for of для переборов. Но это чисто на твоё усмотрение

**Comment by AnnLuschik** [comment]
Исправлено.
